In [1]:
import pandas as pd

In [2]:
df1=pd.read_csv('fake_job_postings.csv')
df1.head()

job_id                                      title            location  \
0       1                           Marketing Intern    US, NY, New York   
1       2  Customer Service - Cloud Video Production      NZ, , Auckland   
2       3    Commissioning Machinery Assistant (CMA)       US, IA, Wever   
3       4          Account Executive - Washington DC  US, DC, Washington   
4       5                        Bill Review Manager  US, FL, Fort Worth   

  department salary_range                                    company_profile  \
0  Marketing          NaN  We're Food52, and we've created a groundbreaki...   
1    Success          NaN  90 Seconds, the worlds Cloud Video Production ...   
2        NaN          NaN  Valor Services provides Workforce Solutions th...   
3      Sales          NaN  Our passion for improving quality of life thro...   
4        NaN          NaN  SpotSource Solutions LLC is a Global Human Cap...   

                                         description  \
0  Food52, a fast-growing, James Beard Award-winn...   
1  Organised - Focused - Vibrant - Awesome!Do you...   
2  Our client, located in Houston, is actively se...   
3  THE COMPANY: ESRI – Environmental Systems Rese...   
4  JOB TITLE: Itemization Review ManagerLOCATION:...   

                                        requirements  \
0  Experience with content management systems a m...   
1  What we expect from you:Your key responsibilit...   
2  Implement pre-commissioning and commissioning ...   
3  EDUCATION: Bachelor’s or Master’s in GIS, busi...   
4  QUALIFICATIONS:RN license in the State of Texa...   

                                            benefits  telecommuting  \
0                                                NaN              0   
1  What you will get from usThrough being part of...              0   
2                                                NaN              0   
3  Our culture is anything but corporate—we have ...              0   
4                              Full Benefits Offered              0   

   has_company_logo  has_questions employment_type required_experience  \
0                 1              0           Other          Internship   
1                 1              0       Full-time      Not Applicable   
2                 1              0             NaN                 NaN   
3                 1              0       Full-time    Mid-Senior level   
4                 1              1       Full-time    Mid-Senior level   

  required_education                   industry              function  \
0                NaN                        NaN             Marketing   
1                NaN  Marketing and Advertising      Customer Service   
2                NaN                        NaN                   NaN   
3  Bachelor's Degree          Computer Software                 Sales   
4  Bachelor's Degree     Hospital & Health Care  Health Care Provider   

   fraudulent  
0           0  
1           0  
2           0  
3           0  
4           0

In [3]:
df1.shape

(17880, 18)

In [4]:
df=df1[['description','requirements','fraudulent']]
df.head()

description  \
0  Food52, a fast-growing, James Beard Award-winn...   
1  Organised - Focused - Vibrant - Awesome!Do you...   
2  Our client, located in Houston, is actively se...   
3  THE COMPANY: ESRI – Environmental Systems Rese...   
4  JOB TITLE: Itemization Review ManagerLOCATION:...   

                                        requirements  fraudulent  
0  Experience with content management systems a m...           0  
1  What we expect from you:Your key responsibilit...           0  
2  Implement pre-commissioning and commissioning ...           0  
3  EDUCATION: Bachelor’s or Master’s in GIS, busi...           0  
4  QUALIFICATIONS:RN license in the State of Texa...           0

In [5]:
###Drop Nan Values
df=df.dropna()

In [6]:
df.shape

(15185, 3)

In [7]:
## Get the Independent Features

X=df.drop('fraudulent',axis=1)

In [8]:
## Get the Dependent features
y=df['fraudulent']

In [9]:
y.value_counts()

0    14473
1      712
Name: fraudulent, dtype: int64

In [10]:
import tensorflow as tf
tf.__version__

'2.0.1'

In [11]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Bidirectional
from tensorflow.keras.layers import Dropout

In [12]:
voc_size=5000

## Onehot Representation:

In [13]:
message = X.copy()

In [14]:
message['description'][1]

"Organised - Focused - Vibrant - Awesome!Do you have a passion for customer service? Slick typing skills? Maybe Account Management? ...And think administration is cooler than a polar bear on a jetski? Then we need to hear you!\xa0We are the Cloud Video Production Service and opperating on a glodal level. Yeah, it's pretty cool. Serious about\xa0delivering a world class product and excellent customer service.Our rapidly expanding business is looking for a talented Project Manager to manage the successful delivery of video projects, manage client communications and drive the production process. Work with some of the coolest brands on the planet and learn from a global team that are representing NZ is a huge way!We are entering the next growth stage of our business and growing quickly internationally. \xa0Therefore, the position is bursting with opportunity for the right person entering the business at the right time.\xa090 Seconds, the worlds Cloud Video Production Service -\xa0http://90

In [15]:
message.reset_index(inplace=True)

In [16]:
import nltk
import re
from nltk.corpus import stopwords

In [17]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to C:\Users\gaurav
[nltk_data]     sahani\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [20]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(message)):
    review = re.sub('[^a-zA-Z]', ' ', message['description'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [21]:
corpus[1]

'organis focus vibrant awesom passion custom servic slick type skill mayb account manag think administr cooler polar bear jetski need hear cloud video product servic opper glodal level yeah pretti cool seriou deliv world class product excel custom servic rapidli expand busi look talent project manag manag success deliveri video project manag client commun drive product process work coolest brand planet learn global team repres nz huge way enter next growth stage busi grow quickli intern therefor posit burst opportun right person enter busi right time second world cloud video product servic http url fbe afac cd c f b eef e e f ca dd second world cloud video product servic enabl brand agenc get high qualiti onlin video content shot produc anywher world fast afford manag seamlessli cloud purchas publish second remov hassl cost risk speed issu work regular video product compani manag everi aspect video project beauti onlin experi grow network rate video profession countri dedic product suc

In [23]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr[1]

[2132,
 2633,
 2026,
 1924,
 321,
 1484,
 3026,
 2404,
 4802,
 3331,
 3451,
 298,
 2357,
 4510,
 2154,
 1524,
 4735,
 1945,
 2056,
 3453,
 986,
 3477,
 1447,
 2329,
 3026,
 4559,
 242,
 4721,
 1578,
 4096,
 3085,
 1044,
 2707,
 4579,
 3001,
 2329,
 1847,
 1484,
 3026,
 3510,
 1329,
 951,
 1550,
 2095,
 4592,
 2357,
 2357,
 1881,
 1487,
 1447,
 4592,
 2357,
 482,
 2779,
 449,
 2329,
 1989,
 4194,
 4332,
 159,
 4298,
 691,
 2623,
 1095,
 3443,
 3995,
 1578,
 2084,
 420,
 2834,
 714,
 3960,
 951,
 1888,
 1690,
 4103,
 3719,
 3199,
 1417,
 2654,
 4164,
 3344,
 420,
 951,
 4164,
 4851,
 3887,
 4579,
 3477,
 1447,
 2329,
 3026,
 3678,
 2978,
 882,
 1060,
 2608,
 2099,
 1877,
 3578,
 4547,
 494,
 494,
 1877,
 1435,
 1821,
 3887,
 4579,
 3477,
 1447,
 2329,
 3026,
 3227,
 159,
 1041,
 3725,
 4991,
 886,
 4335,
 1447,
 1996,
 2305,
 1052,
 1383,
 4579,
 4066,
 10,
 2357,
 4946,
 3477,
 4124,
 3047,
 3887,
 1499,
 1903,
 3724,
 4738,
 553,
 2938,
 4194,
 709,
 1447,
 2329,
 3840,
 2357,
 4532,
 

## Embedding Representation:

In [25]:
sent_length=40
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[1901 1996 2357 ...  196 1745  168]
 [1881 1705  988 ... 3235 2581 4977]
 [   0    0    0 ... 4127 2113 4366]
 ...
 [4808 3349 1636 ... 2650  590 2414]
 [3646 1545 2974 ...  341 4103 4592]
 [ 664 1607   62 ...  678 4182 1464]]


In [26]:
embedded_docs[0]

array([1901, 1996, 2357, 4338, 2510,  172, 4308, 2122,  310, 3416, 2675,
       2675,  310, 1127, 2935, 3538,  310, 2591,  310, 1964, 1368,  478,
       1717, 1891, 2210, 2154, 4194, 2245, 2184, 3084, 4223, 3665,  855,
       2156,  654, 4132, 3315,  196, 1745,  168])

In [27]:
## Creating model
embedding_vector_features=50
model1=Sequential()
model1.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model1.add(Bidirectional(LSTM(100))) ##Just add bidirectional!!, except it would just behave as normal LSTM Model
model1.add(Dropout(0.3))
model1.add(Dense(1,activation='sigmoid'))
model1.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model1.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 40, 50)            250000    
_________________________________________________________________
bidirectional (Bidirectional (None, 200)               120800    
_________________________________________________________________
dropout (Dropout)            (None, 200)               0         
_________________________________________________________________
dense (Dense)                (None, 1)                 201       
Total params: 371,001
Trainable params: 371,001
Non-trainable params: 0
_________________________________________________________________
None


In [28]:
len(embedded_docs),y.shape

(15185, (15185,))

In [29]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [32]:
X_final[1]

array([1881, 1705,  988, 1989, 4206, 4029, 2679, 3887, 1052, 4344, 1447,
       4275, 2623,  159, 2436, 4579, 1656, 2436,   43, 2586, 1501, 3104,
       4195, 2210,  106, 2631, 2574, 4209,  478,  388,  106, 2210, 1332,
       4164, 4653, 1051, 1701, 3235, 2581, 4977])

In [33]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.25, random_state=32)

In [34]:
model1.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=12,batch_size=64)

Train on 11388 samples, validate on 3797 samples
Epoch 1/12
11388/11388 [==============================] - 14s 1ms/sample - loss: 0.1882 - accuracy: 0.9568 - val_loss: 0.1468 - val_accuracy: 0.9576
Epoch 2/12
11388/11388 [==============================] - 10s 836us/sample - loss: 0.0886 - accuracy: 0.9754 - val_loss: 0.1352 - val_accuracy: 0.9621
Epoch 3/12
11388/11388 [==============================] - 10s 843us/sample - loss: 0.0558 - accuracy: 0.9839 - val_loss: 0.1487 - val_accuracy: 0.9652
Epoch 4/12
11388/11388 [==============================] - 10s 898us/sample - loss: 0.0338 - accuracy: 0.9900 - val_loss: 0.1621 - val_accuracy: 0.9666
Epoch 5/12
11388/11388 [==============================] - 10s 894us/sample - loss: 0.0197 - accuracy: 0.9942 - val_loss: 0.2146 - val_accuracy: 0.9671
Epoch 6/12
11388/11388 [==============================] - 10s 919us/sample - loss: 0.0118 - accuracy: 0.9970 - val_loss: 0.1939 - val_accuracy: 0.9679
Epoch 7/12
11388/11388 [=======================

## Model Performance and Accuracy:

In [35]:
y_pred=model1.predict_classes(X_test)

In [37]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[3568,   17],
       [ 104,  108]], dtype=int64)

In [39]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9681327363708191

In [41]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.97      1.00      0.98      3585
           1       0.86      0.51      0.64       212

    accuracy                           0.97      3797
   macro avg       0.92      0.75      0.81      3797
weighted avg       0.97      0.97      0.96      3797

